spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/testauthentication
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
    
