spring:
  datasource:
    username: root
    url: jdbc:mysql://monorail.proxy.rlwy.net:18667/railway
    password: XBEbUdneOAksRcTSbWeklpVypgVNsvTd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'false'
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
    
